---
- name: Update web servers
  hosts: web  
  tasks:
    - name: enable nginx 
      shell: amazon-linux-extras enable nginx1 
    - name: install nginx 
      yum: 
        name: nginx
        state: latest
        update_cache: yes
    - name: start nginx 
      service:
        name: nginx 
        state: started 
